### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [xelenas/prj-rev-bwfs-dasmoto#1]
Instead of having to list `font-weight: bold;` 3 times in your CSS file, you could alternatively specify shared properties for multiple selectors by using commas:

```css
h1, h2, .price {
  font-weight: bold;
}
```

https://github.com/xelenas/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css
